# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: kiku16
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: line-to-googlephoto
# "service" is the name of this project. This will also be added to your AWS resource names.
service: line-to-googlephoto

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  environment:
    L_CHANNEL_SECRET: ${env:L_CHANNEL_SECRET}
    L_CHANNEL_ACCESS_TOKEN: ${env:L_CHANNEL_ACCESS_TOKEN}
    G_CLIENT_ID: ${env:G_CLIENT_ID}
    G_CLIENT_SECRET: ${env:G_CLIENT_SECRET}
    G_REFRESH_TOKEN: ${env:G_REFRESH_TOKEN}
    G_ALBUM_ID: ${env:G_ALBUM_ID}
    START_DATETIME: ${env:START_DATETIME}
    END_DATETIME: ${env:END_DATETIME}

functions:
  callback:
    handler: handler.callback
    events:
      - httpApi:
          path: /
          method: post
    timeout: 180
    memorySize: 512

plugins:
  - serverless-offline
